name: API Compatibility
on:
  merge_group:
  push:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches:
    - "**"
    paths-ignore:
    - '**/*.md'
jobs:
  apidiff:
    runs-on: ubuntu-latest
    if: github.base_ref
    steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - name: Add GOBIN to PATH
      run: echo "$(go env GOPATH)/bin" >>$GITHUB_PATH
    - name: Install apidiff cmd
      run: go install golang.org/x/exp/cmd/apidiff@latest
    - name: Checkout base code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}
        path: "base"
    - name: Capture apidiff baseline
      run: apidiff -m -w ../baseline.bin .
      working-directory: "base"
    - name: Checkout updated code
      uses: actions/checkout@v4
      with:
        path: "updated"
    - name: Run apidiff check
      run: apidiff -m -incompatible ../baseline.bin .
      working-directory: "updated"
