name: Fuzzing
on:
  merge_group:
  push:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches:
    - "**"
    paths-ignore:
    - '**/*.md'
jobs:
  test:
    name: Fuzz
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -trimpath
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - name: Run any fuzzing tests
      run: go test -v -run=^Fuzz -test.fuzztime=5m ./...
