name: FVT
on:
  merge_group:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "**"
jobs:
  fvt:
    name: Test with Kafka ${{ matrix.kafka-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.21.x]
        kafka-version: [3.3.2, 3.4.1, 3.5.1]
    env:
      DEBUG: true
      GOFLAGS: -trimpath
      KAFKA_VERSION: ${{ matrix.kafka-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2
      id: buildx
    - name: Build FVT Docker Image
      uses: docker/bake-action@master
      with:
        builder: ${{ steps.buildx.outputs.name }}
        files: docker-compose.yml
        load: true
        set: |
          *.cache-from=type=gha,scope=${{ github.workflow }}
          *.cache-to=type=gha,scope=${{ github.workflow }},mode=max
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test (Functional)
      run: make test_functional
